- onException:
    exception:
      - java.lang.Exception
    handled:
      constant: true
    steps:
      - process:
          ref: exceptionProcessor
      - marshal:
          json: { }

- route:
    id: doctor-appointment-list-route
    from:
      uri: direct:doctor-appointment-list
      steps:
        - process:
            ref: appointmentListProcessor
        - marshal:
            json: { }

- route:
    id: doctor-appointment-count-route
    from:
      uri: direct:doctor-appointment-count
      steps:
        - process:
            ref: appointmentCountProcessor
        - marshal:
            json: { }

- route:
    id: doctor-appointment-get-route
    from:
      uri: direct:doctor-appointment-get
      steps:
        - process:
            ref: appointmentGetProcessor
        - marshal:
            json: { }

- route:
    id: doctor-appointment-create-route
    from:
      uri: direct:doctor-appointment-create
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.appointment.CreateAppointmentDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: appointmentCreateProcessor
        - marshal:
            json: { }

- route:
    id: doctor-appointment-update-route
    from:
      uri: direct:doctor-appointment-update
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.appointment.UpdateAppointmentDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: appointmentUpdateProcessor
        - marshal:
            json: { }

- route:
    id: doctor-appointment-restore-route
    from:
      uri: direct:doctor-appointment-restore
      steps:
        - process:
            ref: appointmentRestoreProcessor
        - marshal:
            json: { }

- route:
    id: doctor-appointment-delete-route
    from:
      uri: direct:doctor-appointment-delete
      steps:
        - process:
            ref: appointmentDeleteProcessor
        - marshal:
            json: { }

- route:
    id: public-appointment-list-route
    from:
      uri: direct:public-appointment-list
      steps:
        - process:
            ref: appointmentListProcessor
        - marshal:
            json: { }

- route:
    id: public-appointment-count-route
    from:
      uri: direct:public-appointment-count
      steps:
        - process:
            ref: appointmentCountProcessor
        - marshal:
            json: { }

- route:
    id: public-appointment-get-route
    from:
      uri: direct:public-appointment-get
      steps:
        - process:
            ref: appointmentGetProcessor
        - marshal:
            json: { }

- route:
    id: public-appointment-create-route
    from:
      uri: direct:public-appointment-create
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.appointment.CreateAppointmentDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: appointmentCreateProcessor
        - marshal:
            json: { }

- route:
    id: staff-appointment-list-route
    from:
      uri: direct:staff-appointment-list
      steps:
        - process:
            ref: appointmentListProcessor
        - marshal:
            json: { }

- route:
    id: staff-appointment-update-route
    from:
      uri: direct:staff-appointment-update
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.appointment.UpdateAppointmentDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: appointmentUpdateProcessor
        - marshal:
            json: { }