- onException:
    exception:
      - java.lang.Exception
    handled:
      constant: true
    steps:
      - process:
          ref: exceptionProcessor
      - marshal:
          json: { }

- route:
    id: doctor-medical-record-list-route
    from:
      uri: direct:doctor-medical-record-list
      steps:
        - process:
            ref: medicalRecordListProcessor
        - marshal:
            json: { }

- route:
    id: doctor-medical-record-count-route
    from:
      uri: direct:doctor-medical-record-count
      steps:
        - process:
            ref: medicalRecordCountProcessor
        - marshal:
            json: { }

- route:
    id: doctor-medical-record-get-route
    from:
      uri: direct:doctor-medical-record-get
      steps:
        - process:
            ref: medicalRecordGetProcessor
        - marshal:
            json: { }

- route:
    id: doctor-medical-record-create-route
    from:
      uri: direct:doctor-medical-record-create
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.medicalRecord.CreateMedicalRecordDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: medicalRecordCreateProcessor
        - marshal:
            json: { }

- route:
    id: doctor-medical-record-update-route
    from:
      uri: direct:doctor-medical-record-update
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.medicalRecord.UpdateMedicalRecordDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: medicalRecordUpdateProcessor
        - marshal:
            json: { }

- route:
    id: doctor-medical-record-restore-route
    from:
      uri: direct:doctor-medical-record-restore
      steps:
        - process:
            ref: medicalRecordRestoreProcessor
        - marshal:
            json: { }

- route:
    id: doctor-medical-record-delete-route
    from:
      uri: direct:doctor-medical-record-delete
      steps:
        - process:
            ref: medicalRecordDeleteProcessor
        - marshal:
            json: { }
