- onException:
    exception:
      - java.lang.Exception
    handled:
      constant: true
    steps:
      - process:
          ref: exceptionProcessor
      - marshal:
          json: { }

- route:
    id: admin-user-list-route
    from:
      uri: direct:admin-user-list
      steps:
        - process:
            ref: userListProcessor
        - marshal:
            json: { }

- route:
    id: public-user-list-route
    from:
      uri: direct:public-user-list
      steps:
        - process:
            ref: userListProcessor
        - marshal:
            json: { }

- route:
    id: admin-user-statistics-route
    from:
      uri: direct:admin-user-statistics
      steps:
        - process:
            ref: userStatisticsProcessor
        - marshal:
            json: { }

- route:
    id: admin-user-count-route
    from:
      uri: direct:admin-user-count
      steps:
        - process:
            ref: userCountProcessor
        - marshal:
            json: { }

- route:
    id: admin-user-get-route
    from:
      uri: direct:admin-user-get
      steps:
        - process:
            ref: userGetProcessor
        - marshal:
            json: { }

- route:
    id: public-user-statistics-route
    from:
      uri: direct:public-user-statistics
      steps:
        - process:
            ref: userStatisticsProcessor
        - marshal:
            json: { }

- route:
    id: admin-user-create-route
    from:
      uri: direct:admin-user-create
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.user.CreateUserDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: userCreateProcessor
        - marshal:
            json: { }

- route:
    id: admin-user-update-route
    from:
      uri: direct:admin-user-update
      steps:
        - setHeader:
            name: X-DTO-Class
            constant: com.camel.clinic.dto.user.UpdateUserDto
        - process:
            ref: requestDeserializerProcessor
        - process:
            ref: validationProcessor
        - process:
            ref: userUpdateProcessor
        - marshal:
            json: { }


- route:
    id: admin-user-delete-route
    from:
      uri: direct:admin-user-delete
      steps:
        - process:
            ref: userDeleteProcessor
        - marshal:
            json: { }
